### ISSUE TITLE
Company Owner in Company module

### ISSUE THREAD

**Issue by markreme** [dotproject/dotProject#49] opened 2019-01-19 22:09 UTC
The dropdown in the company owner box in the company module is not working.  It only lists myself as the available owner.

Is there away to let me pick the name from the contacts list?

**Comment by ajdonnison** [comment] 2019-01-21 10:58
The dropdown lists users, not contacts.  You have to be a user before you can own a company - and remember we aren't talking about proprietorial ownership here, but which users is responsible for projects associated with this entry.

**Comment by ajdonnison** [comment] 2019-04-03 03:00
Seeing as I believe this is working as intended, I'm closing this issue.

**Closed by ajdonnison** 2019-04-03 03:00 UTC
